name: Deploy to AWS S3

on:
  push:
    branches:
      - KL-159/리팩토링

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate  
          echo "YARN_VERSION=$(yarn -v)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          yarn install

      - name: Set Environment Variables
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
          VITE_DEFAULT_IMAGE: ${{ secrets.VITE_DEFAULT_IMAGE }}
        run: |
          echo "VITE_APP_API_URL=${VITE_APP_API_URL}" >> .env
          echo "VITE_DEFAULT_IMAGE=${VITE_DEFAULT_IMAGE}" >> .env

      - name: Build project
        run: yarn build

      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version

      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region us-east-1 \
            dist s3://klkl-frontend \
            --delete

      - name: Create Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUD_FRONT_ID \
            --paths /*
